# id: CQ_001
# question:
#   Given a publication PID, find all articles that cite it plus those cited in the
#   publication itself.

PREFIX cito: <http://purl.org/spar/cito/>
PREFIX datacite: <http://purl.org/spar/datacite/>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX literal: <http://www.essepuntato.it/2010/06/literalreification/>

SELECT DISTINCT ?pid_value
WHERE {
    VALUES ?article_id_value {"10.1021/acs.est.7b05039"}
    ?article datacite:hasIdentifier [
        literal:hasLiteralValue ?article_id_value
    ] .
    {
        ?article cito:cites [
            a fabio:ScholarlyWork ;
            datacite:hasIdentifier [
                literal:hasLiteralValue ?pid_value
            ]
        ] .
    }
    UNION
    {
    ?article_citing a fabio:ScholarlyWork ;
        cito:cites ?article ;
        datacite:hasIdentifier [
            literal:hasLiteralValue ?pid_value ;
            datacite:usesIdentifierScheme datacite:doi 
        ] .
    }
}
